# Generated by Django 5.0.4 on 2024-04-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='Address',
        ),
    ]
